### ISSUE TITLE
Assignment troubles

### ISSUE THREAD

**Issue by ndroger1** [SOS598-RDM/rdm-community#6]
![image](https://user-images.githubusercontent.com/54640427/74880665-e8ef1000-5328-11ea-8bce-f37effd77b12.png)
 When I try yo input the listings I get either and unexpected '>' error or an unexpected'/' error. I have checked the syntax with the example in the assignment and and not sure what is wrong.

**Comment by srearl** [comment]
Hi @ndroger1 - Make sure: 1. that you are working with the homework repository that I created for you using San Francisco data not the San Diego repository that I used in class, and 2. in your homework repository that you are working with the airbnb-san-francisco.Rmd file that is in the R directory of the repository that I created for you.

**Comment by ndroger1** [comment]
Thanks, I have the assignment almost complete but now it is saying neighbourhood is not an object when I run the last set of code
![image](https://user-images.githubusercontent.com/54640427/74982403-49e21b00-53f1-11ea-8c2f-3778ca5ab304.png)

**Comment by ndroger1** [comment]
Never mind got it
